# Generated by Django 4.2.7 on 2024-01-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehreer', '0002_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-id']},
        ),
    ]
