# Generated by Django 4.2.7 on 2024-01-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehreer', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp', '-id']},
        ),
    ]
