# Generated by Django 4.2.7 on 2024-01-21 10:52

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', django_quill.fields.QuillField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
