# Generated by Django 4.2.7 on 2023-11-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comments_bids_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lister',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
